version: '{branch}-build-{build}'

shallow_clone: true

notifications:
  - provider: Email
    to:
    - fusioninventory-commit@lists.alioth.debian.org
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
  - provider: Webhook
    url: https://hooks.aethonan.pro/appveyor/-1001137546384/
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true

skip_commits:
  files:
    - '**/*.md'
    - '*.txt'

install:
  - cinst nsis --version 3.02
  - cinst pandoc --version 1.17.0.2
  - cd Perl\Scripts
  - .\install-gnu-utilities-collection.bat
  - .\install-strawberry-perl-package-for-fusioninventory-agent.bat
  - .\install-fusioninventory-agent.bat
  - .\patch-fusioninventory-agent.bat
  - .\update-ids-repositories.bat
  - cd ..\..

test: off

build_script:
  - cd NSIS
  - .\FusionInventory-Agent.bat
  - dir

artifacts:
  - path: NSIS/*.txt,Perl/Scripts/*build.log*
    name: logs
  - path: NSIS/*.exe
    name: exes
  - path: NSIS/*.md5,NSIS/*.sha1,NSIS/*.sha256
    name: chks

deploy:
  description: 'Public Release'
  provider: GitHub
  auth_token:
    secure: YBbTdTUzqgeUZl4OJKHvP0TFOtBR+omjfsUcxgf92+ht/4jCqCDbd/rbaswueKTe
  artifact: exes,chks
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
